-- =============================================================================
-- 20260901120000_product_events.sql
-- =============================================================================
-- Product telemetry counters (1.3.0, Block 3).
--
-- WHY THIS TABLE EXISTS
-- 1.3.0's point is not the tax calendar, it is learning. D-2 (who the ICP
-- actually is — small limited company, sole trader, or freelancer) is
-- currently answered by two competing guesses. This table is the evidence
-- that replaces them. Ship 1.3.0 without it and nothing is learned.
--
-- WHAT IT MAY NEVER HOLD
-- Counters and categorical values only. No free text, no document content,
-- no amounts. That rule is enforced structurally, not by convention:
--   * there is no text column that can carry a phrase — `event_key` and
--     `dimension` are constrained by regex to lowercase identifiers with a
--     hard length cap, so a store name, an OCR line, or a note cannot fit;
--   * there is no numeric column other than `count`, so a lira amount has
--     nowhere to land.
-- A client-side scrubber is the last line of defence, not the first. The
-- event is designed so it never carries the data in the first place.
--
-- WRITE SEMANTICS — D-14 (2026-09-01)
-- This is a counter table, but the sync engine is last-write-wins. Naive
-- overwrite would make two devices silently eat each other's increments, in
-- the very release whose Block 2 exists to stop silent loss.
--
-- Resolution: the device is part of the unique key. Each device writes the
-- ABSOLUTE count it has observed for a given (event_key, dimension, day);
-- readers aggregate with sum(). Overwrite is therefore the CORRECT operation
-- — no device can ever touch another device's row — and the upload is
-- idempotent by construction: a retry, a lost response, or a duplicated batch
-- all converge on the same value, with no delta bookkeeping on the client.
--
-- The rejected alternative (`count = count + excluded.count` with client
-- deltas) is not idempotent: if the server commits and the response is lost,
-- the client resends the same delta and double-counts. Fixing that needs
-- per-batch idempotency keys plus a server-side seen-batches table — strictly
-- more machinery than one `device_id` column.
--
-- CONSENT — D-15 (2026-09-01)
-- Opt-out, resting on KVKK art. 5/2-f (legitimate interest), NOT explicit
-- consent. The load-bearing facts: the payload carries no free text, amount,
-- or document content (enforced above); it attaches to an already-identified
-- account rather than creating a new identity; there is no third-party
-- processor and no cross-border transfer; and the user can switch it off in
-- one tap. Pending KVKK Compliance Officer review (Block 3 F4) — if that
-- review lands on opt-in, only the default and the flow change, not this
-- schema.
--
-- Conventions match 20260528130000_user_corrections.sql.
-- =============================================================================

create table public.product_events (
  id            uuid          primary key default gen_random_uuid(),
  user_id       uuid          not null references auth.users(id) on delete cascade,

  -- Deliberately NO foreign key, and deliberately nullable.
  --
  -- The company (space) model arrives in 1.4.0: `companies`,
  -- `company_members` and the `is_company_member()` helper do not exist in
  -- any migration yet. Writing `references public.companies(id)` here would
  -- simply fail. CLAUDE.md's "every synced table carries company_id" rule is
  -- honoured by carrying the column now, under its stated 1.3.0 exception
  -- that the value is NULL. 1.4.0 backfills it and adds the constraint.
  company_id    uuid          null,

  -- Random per-install UUID generated by the client — NOT a hardware
  -- identifier. IDFV / Android ID / advertising ids are out of bounds
  -- (KVKK, and Apple's own rules). Reinstalling the app produces a new value,
  -- which is the correct and disclosed behaviour: it costs a small amount of
  -- cross-install continuity and buys a much smaller privacy surface.
  --
  -- Length-capped so it cannot be repurposed as a free-text smuggling route.
  device_id     text          not null
                              constraint product_events_device_id_shape
                              check (device_id ~ '^[0-9a-f-]{16,64}$'),

  -- The event name, e.g. `scan_started`. Lowercase identifier, 3..48 chars.
  -- The regex is the structural half of the "no free text" rule: no spaces,
  -- no punctuation, no uppercase, no digits-first — a sentence, a store name
  -- or an OCR fragment cannot be encoded here.
  event_key     text          not null
                              constraint product_events_event_key_shape
                              check (event_key ~ '^[a-z][a-z0-9_]{2,47}$'),

  -- Optional categorical breakdown, e.g. the taxpayer-profile bucket on
  -- `tax_profile_completed`. Same shape rule, shorter cap.
  --
  -- NOT NULL with an empty-string sentinel on purpose. If this were nullable,
  -- Postgres' default "nulls are distinct" rule would let the same
  -- (user, device, event_key, day) insert twice and the ON CONFLICT target
  -- would not match, quietly reintroducing the double-count this design
  -- exists to prevent. `UNIQUE NULLS NOT DISTINCT` would also solve it but
  -- assumes PG >= 15; the sentinel is correct on every version.
  dimension     text          not null default ''
                              constraint product_events_dimension_shape
                              check (
                                dimension = ''
                                or dimension ~ '^[a-z0-9][a-z0-9_]{0,31}$'
                              ),

  -- Calendar day in UTC. Day granularity, never a timestamp per occurrence:
  -- a per-event timestamp would turn this from a counter into a timeline of
  -- what the user did and when.
  day           date          not null,

  -- Absolute occurrences this device observed for the key on that day.
  -- Upper bound is a sanity rail against a client-side loop bug poisoning
  -- the aggregate; no honest counter approaches it.
  count         integer       not null default 0
                              constraint product_events_count_range
                              check (count >= 0 and count <= 1000000),

  created_at    timestamptz   not null default timezone('utc', now()),
  updated_at    timestamptz   not null default timezone('utc', now()),

  -- The ON CONFLICT target for the client's idempotent upsert.
  constraint product_events_identity_key
    unique (user_id, device_id, event_key, dimension, day)
);

-- Per-user reads (the user's own data, and KVKK access/erasure requests).
create index product_events_user_day_idx
  on public.product_events(user_id, day);

-- The analysis query that answers D-2 runs across users, one event at a time.
create index product_events_key_day_idx
  on public.product_events(event_key, day);

create trigger trg_product_events_updated_at
  before update on public.product_events
  for each row execute function public.set_updated_at();

comment on table public.product_events is
  'Per-device, per-day product telemetry counters. Counters and categorical '
  'values only — no free text, no amounts, no document content (enforced by '
  'the event_key/dimension CHECK constraints, not by convention). Unique on '
  '(user_id, device_id, event_key, dimension, day) so each device owns its '
  'own row: writes are absolute and idempotent, and readers sum() across '
  'devices. Owner-only via RLS. See D-14 / D-15.';

comment on column public.product_events.company_id is
  'Nullable and FK-less until 1.4.0 ships the companies table. Carried now so '
  'the 1.4.0 backfill has a column to write into.';

comment on column public.product_events.device_id is
  'Random per-install UUID from the client. Never a hardware identifier.';

comment on column public.product_events.count is
  'ABSOLUTE count observed by this device for this key/day — not a delta. '
  'Resending the same value is a no-op, which is what makes upload retries '
  'safe.';

-- -----------------------------------------------------------------------------
-- RLS — enable + force (the auto_enable_rls() event trigger already does this;
-- repeated here so the migration is self-contained) plus the standard
-- owner-only policy set.
--
-- Scoped on user_id = auth.uid() for this release. The
-- is_company_member(company_id) form lands in 1.4.0 alongside the companies
-- table, following the transitional pattern in CLAUDE.md.
--
-- DELETE is granted deliberately: telemetry rows are the user's personal data
-- and KVKK's erasure right has to reach them. Account deletion is covered by
-- the ON DELETE CASCADE above.
-- -----------------------------------------------------------------------------
alter table public.product_events enable row level security;
alter table public.product_events force row level security;

create policy "product_events_select_own"
  on public.product_events for select
  using (auth.uid() = user_id);
create policy "product_events_insert_own"
  on public.product_events for insert
  with check (auth.uid() = user_id);
create policy "product_events_update_own"
  on public.product_events for update
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);
create policy "product_events_delete_own"
  on public.product_events for delete
  using (auth.uid() = user_id);
